### ISSUE TITLE
multiple newrelic.ini configs for php-agent

### ISSUE THREAD

**Issue by jnankin** [escapestudios-cookbooks/newrelic#143]
I've set the following and I'm running Ubuntu 14.04:

node.default['newrelic']['php_agent']['config_file'] = "/etc/php5/mods-available/newrelic.ini"

I now have a config file in the following places after running the cookbook:
1) "/etc/php5/mods-available/newrelic.ini"
2) a symlink to "/etc/php5/mods-available/newrelic.ini" at "/etc/php5/cli/conf.d/20-newrelic.ini"
3) "/etc/php5/cli/conf.d/newrelic.ini"

The file at the third location is loading the extension again, and this is causing a PHP Warning.  Additionally, the file at the third location is different from the files at 1&2 and does not contain my license key that I told the cookbook to use.

Where is that third config file coming from?  Is the installer for the extension creating this file itself?

**Comment by danbarker** [comment]
I've just come across this, and implemented the fix described - e.g. setting the config_file_to_be_deleted to '/etc/php/5.6/cli/conf.d/newrelic.ini'. 

I noticed while doing this that this only actually fixes this problem in one place, and that the newrelic-php5 package also installs the same empty newrelic config to the following locations on my machines:
```
/etc/php/5.6/fpm/conf.d/newrelic.ini
/etc/php/7.0/mods_available/conf.d/newrelic.ini
```

I was contemplating turning config_file_to_be_deleted into an array and submitting a PR, but thought that I would run this past you first @djoos . For now, I have not set my config_file_to_be_deleted but have rather added the following to our newrelic recipe (similar to @jnankin 's suggestion) , after `include_recipe 'newrelic::php_agent'`: (I 
```
  if node["platform_version"] == "14.04"
      file '/etc/php/5.6/cli/conf.d/newrelic.ini' do
        action :delete
      end
      file "/etc/php/5.6/fpm/conf.d/newrelic.ini" do
        action :delete
      end
      file "/etc/php/7.0/mods-available/newrelic.ini" do
        action :delete
      end
  end
```

**Comment by ynuyasha** [comment]
i'm in the same problem as describe @danbarker 
@djoos Any chance to transform node['newrelic']['php_agent']['config_file_to_be_deleted'] into an array of strings so we can delete multiple files that newrelic-install create?
