### ISSUE TITLE
Override app_location attribute

### ISSUE THREAD

**Issue by randeffects** [escapestudios-cookbooks/newrelic#154]
I can't seem to override the attribute `node['newrelic']['java_agent']['app_location']` in order to set my tomcat location for the java agent install.  I endup with the error:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of sudo java -jar /opt/newrelic/java/newrelic.jar -s /opt/newrelic/java install ----
STDOUT: Feb 10, 2015 00:01:16 +0000 [3627 1] com.newrelic INFO: Agent is using Logback
***** ( ( o))  New Relic Java Agent Installer
***** Installing version 3.9.0 ...
Could not edit start script because:
.:. Could not locate a Tomcat, Jetty, JBoss, JBoss7 or Glassfish instance in /opt/newrelic/java
Try re-running the install command with the -s <AppServerRootDirectory> option or from <AppServerRootDirectory>/newrelic.
If that doesn't work, locate and edit the start script manually.
```
I am attempting to set `node['newrelic']['java_agent']['app_location']` in my application recipe using the line `node.override['newrelic']['java_agent']['app_location'] = /opt/myapp/tomcat` so that the command that runs ends up like: `sudo java -jar /opt/newrelic/java/newrelic.jar -s /opt/myapp/tomcat install`

**Comment by djoos** [comment]
Hi @randeffects,

sorry for the delay in getting back to you. Are you able to set the node['newrelic']['java_agent']['install_dir'] to /opt/myapp/tomcat ?

Thanks in advance for your feedback!

Kind regards,
David

**Comment by djoos** [comment]
Hi @randeffects,

please do get in touch if this issue is still a problem for you with the latest version of the cookbook.

Have a great evening!

Kind regards,
David
