### ISSUE TITLE
Default value for default[:newrelic][:java_agent][:jar_file] breaks agent startup

### ISSUE THREAD

**Issue by ajkerr** [escapestudios-cookbooks/newrelic#164]
The Java agent installer adds the following line to the catalina.sh Tomcat script (and perhaps elsewhere):

```
# ---- New Relic switch automatically added to start command on 2015 Mar 24, 14:55:20
NR_JAR=/usr/share/tomcat8/newrelic/newrelic.jar; export NR_JAR
CATALINA_OPTS="$CATALINA_OPTS -javaagent:$NR_JAR"; export CATALINA_OPTS
```

Now that #160 makes the value for java_agent jar_file be used, the default value in the attributes file causes Tomcat startup to fail because the jar file is not the same.

I propose changing the default value in the java_agent attributes file to:

```ruby
default[:newrelic][:java_agent][:jar_file] = "newrelic.jar"
```

**Comment by cog-piisang** [comment]
Hey, sorry for that (I'm @lauripiisang , author of #160 ). Feel free to make a PR or stay on '= 2.8.0' until I fix it.

**Comment by djoos** [comment]
Hi @ajkerr,

as mentioned in #173, this should now have been addressed - do give me a shout here in case you're still experiencing the issue!

Kind regards,
David
