### ISSUE TITLE
newrelic-daemon stopped by subsequent chef runs of php_agent

### ISSUE THREAD

**Issue by sronderos-atlassian** [escapestudios-cookbooks/newrelic#167]
When using `default['newrelic']['php_agent']['startup_mode'] = 'agent'` each run of chef would stop the newrelic-daemon process that was started by the agent.

This is the output from the 2nd chef run:

```
Recipe: newrelic::php_agent
  * package[newrelic-php5-broken] action remove (up to date)
  * package[newrelic-php5] action install (up to date)
  * execute[newrelic-install] action nothing (skipped due to action :nothing)
  * service[newrelic-daemon] action nothing (up to date)
  * execute[newrelic-php5enmod] action nothing (skipped due to action :nothing)
  * template[/etc/php5/conf.d/newrelic.ini] action create (up to date)
  * log[newrelic-daemon startup mode: agent] action write

  * service[newrelic-daemon] action disable (up to date)
  * service[newrelic-daemon] action stop
    - stop service service[newrelic-daemon]
  * execute[newrelic-backup-cfg] action run (skipped due to only_if)
  * execute[newrelic-backup-key] action run (skipped due to only_if)
  * service[stub_service] action nothing (skipped due to action :nothing)
```

For now I'm using the `external` agent startup mode and everything is working fine.  I believe that the problem is related to the recipe stopping the service regardless of who has started it. Line 134 of php_agent.rb

I'm using Chef Client, version 11.16.4

**Comment by djoos** [comment]
Hi @sronderos-atlassian,

this issue is related to #58. No one ever came up with an elegant solution for this (please do read my reply on 19/02/2014).

Happy to have a (re)look at it if you have any suggestion to a solution though!

Kind regards,
David
