### ISSUE TITLE
newrelic::php_agent web_server restart/reload handling should be graceful

### ISSUE THREAD

**Issue by john-coleman-w** [escapestudios-cookbooks/newrelic#170]
Restarting apache2 is fine, but for php-fpm, it can be gracefully restarted using reload.
Add attribute node['newrelic']['php_agent']['web_server']['service_action'] and use it for resources notifying service node['newrelic']['php_agent']['web_server']['service_name']

**Comment by john-coleman-w** [comment]
https://github.com/escapestudios-cookbooks/newrelic/pull/171 for your consideration.
Also fixes a test and adds vagrant-wrapper gem to Gemfile.

**Comment by djoos** [comment]
Hi @john-coleman-w,

"restart" has been replaced by "reload" in a recent release. Does that work for you?

Thanks in advance for your feedback!

Kind regards,
David
