### ISSUE TITLE
Breaking change in today's release, attribute must be of type String that was previously boolean

### ISSUE THREAD

**Issue by martinb3** [escapestudios-cookbooks/newrelic#175]
Hi there --

Before today's release, one could do this:
```
override['newrelic']['application_monitoring']['daemon']['ssl'] = true
```

The template contained (with `:daemon_ssl => node['newrelic']['application_monitoring']['daemon']['ssl'],`:
```
# Default: false
<% if @daemon_ssl.nil? %>
#ssl=false
<% else %>
ssl=<%= @daemon_ssl %>
<% end %>
```

The newest release also has the same template content, but the new resource has a different constraint:

```
attribute :daemon_ssl, :kind_of => String, :default => nil
```

For users who were setting that as a boolean, the new behavior actually breaks backwards compatibility. I'd recommend either a major version bump, or going back to allowing boolean values.

Thanks!

- Martin

/CC @niven01

**Comment by martinb3** [comment]
FWIW, this appears to be the case for a number of String attributes that previously supported boolean values. And I don't actually see it documented anywhere that it should be a String or boolean, so that may also be worth doing.

**Comment by djoos** [comment]
Hi Martin,

thanks for getting in touch.

Before turning the recipes into resources it was dubious whether daemon_ssl was a String or TrueClass/FalseClass. Now the resource describes the attribute as String a former boolean will throw this error...

I had a quick look in the [New Relic PHP agent docs](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration) and there the type is set to "Boolean".

We'll need to have a look and x-reference the PHP agent and server monitor attributes in the NR doc to the attributes in the resources just to make sure they are in line with each other.

Kind regards,
David

**Comment by martinb3** [comment]
I'll try to put a PR together to clean some of this up. Maybe we can support both.

**Comment by djoos** [comment]
:+1:

@ anyone running into the issue right now: go for 'true' to get round the issue that got introduced in 2.11.0 until there's a fix in place.

Hope this helps!

**Comment by jorhett** [comment]
Glad to see this is tracked, it slapped us too. Might want to rename this issue to reflect it's nature, as the name is unspecific at the moment.

**Comment by martinb3** [comment]
Updated the title to reflect the issue better.

**Comment by djoos** [comment]
What about using...
```
    def to_boolean(variable)
      if variable.is_a?(TrueClass) || variable.is_a?(FalseClass)
        variable
      else
        variable == 'true' || variable == 1
      end
    end
```
...allowing any old String or 1 to be converted to what the resource defines ([String] => [TrueClass, FalseClass] for relevant attributes that are Boolean in the NR docs). But the to_boolean is only used for the recipe-centered users - anyone directly using the LWRP will have to pass in true or false.

Let me know what you think!

Kind regards,
David
