### ISSUE TITLE
breaking change -- PHP file rewritten without configuration values

### ISSUE THREAD

**Issue by jorhett** [escapestudios-cookbooks/newrelic#177]
I'm still investigating why, but our PHP ini files were rewritten without any of our custom attributes after this cookbook update was applied. 

    @@ -87,7 +87,7 @@
       ;          list is considered the 'primary' application name and must be unique
       ;          for each account / license key.
       ;
      -newrelic.appname = "Dev3 - Live"
      +;newrelic.appname = "PHP Application"

       ;
       ; Beginning with version 3.0 of the agent, the daemon can be automatically
      @@ -119,7 +119,7 @@
       ; Default: none
       ; Info   : Sets the name of the file to send daemon log messages to.
       ;
      -newrelic.daemon.logfile = "/var/log/newrelic/newrelic-daemon.log"
      +newrelic.daemon.logfile = ""

       ;
       ; Setting: newrelic.daemon.loglevel
      @@ -153,7 +153,7 @@
       ;          used for processing requests from each agent. The minimum is 4 and
       ;          the maximum is 128.
       ;
      -newrelic.daemon.max_threads = 8
      +;newrelic.daemon.max_threads = 8

       ;
       ; Setting: newrelic.daemon.ssl
      @@ -167,7 +167,7 @@
       ;          PEM-encoded certificate file, or a directory that contains a list
       ;          of such files, using the following two options.
       ;
      -newrelic.daemon.ssl = true
      +;newrelic.daemon.ssl = false

       ;
       ; Setting: newrelic.daemon.ssl_ca_path

**Comment by jorhett** [comment]
Nevermind. We were using a local template to fix problems fixed in a Pull request you merged a while back. We have removed the local template ;)

**Comment by djoos** [comment]
Thanks for self-healing the issue @jorhett ;-)

Have a great weekend!
