### ISSUE TITLE
Option license must be a kind of String! You passed false.

### ISSUE THREAD

**Issue by martinb3** [escapestudios-cookbooks/newrelic#178]
Seeing another false/nil difference from today's release. Perhaps the license check should be for falsey, not nil.

https://github.com/escapestudios-cookbooks/newrelic/blob/master/libraries/helpers.rb#L9-L12

**Comment by djoos** [comment]
Hi @martinb3,

the license should be a String and when setting it to false, the check should flag this... That actually seems ok to me, unless I got it at the wrong end of the stick!

Kind regards,
David

**Comment by martinb3** [comment]
Hi David,

The check didn't actually fire -- it fired at the resource validation first. We actually have some cases where we `include_recipe 'newrelic'`, and if a license key is set, things 'just work', but if a license key is set to false, it's a no-op.

With today's changes, false is no longer a no-op, an exception is raised.

We did used to guard against nil, just never against false since the newrelic cookbook used to handle that:
```
include_recipe 'newrelic' unless node['newrelic']['license'].nil?
```

We're going to have to change those to:
```
include_recipe 'newrelic' unless node['newrelic']['license']
```

**Comment by djoos** [comment]
Ah ok, got it.

What about
```
include_recipe 'newrelic' if node['newrelic']['license'].is_a?(String)
```
?

**Comment by martinb3** [comment]
That works, just doesn't cover the empty string `''`, which someone might pass to turn off NR as well. I figured ```include_recipe 'newrelic' unless node['newrelic']['license'] && !node['newrelic']['license'].empty?``` covered the most cases (false, nil, '', 'an-actual-licensekey').

**Comment by djoos** [comment]
Another one that would make sure it's a non-blank String:
```
include_recipe 'newrelic' if node['newrelic']['license'].is_a?(String) && !node['newrelic']['license'].blank?
```
