### ISSUE TITLE
Option ssl must be a kind of String!  You passed false.

### ISSUE THREAD

**Issue by martinb3** [escapestudios-cookbooks/newrelic#179]
Hello! It looks like the latest release fails in test-kitchen. It looks like server_monitor's [SSL parameter is set to a String still](https://github.com/escapestudios-cookbooks/newrelic/blob/master/resources/server_monitor.rb#L16), but it's [being passed a boolean](https://github.com/escapestudios-cookbooks/newrelic/blob/master/recipes/server_monitor_agent.rb#L13) in the recipe.

**Comment by martinb3** [comment]
I don't see where the latest few commits ran in Travis, but even the unit tests are failing for me on Chef 12.2.

**Comment by martinb3** [comment]
Submitted #180 to fix it.

**Comment by djoos** [comment]
FYI: kind_of for SSL got fixed in 59b5aff370a5bfa646bc949b2ead3508558c9079
