### ISSUE TITLE
Java_agent fails

### ISSUE THREAD

**Issue by abhi-vaidya** [escapestudios-cookbooks/newrelic#185]
Hi 

As per README, I have included recipe "newrelic::java_agent"  and added newrelicyml defination. but java_agent recipe fails while setup default setup. here is the error I get

.:. Could not locate a Tomcat, Jetty, JBoss, JBoss7 or Glassfish instance in /opt/newrelic/java
Try re-running the install command with the -s <AppServerRootDirectory> option or from <AppServerRootDirectory>/newrelic.
If that doesn't work, locate and edit the start script manually.
No need to create New Relic configuration file because:
 .:. A config file already exists: /opt/newrelic/java/newrelic.yml
***** Install incomplete
***** Next steps:
For help completing the install, see https://newrelic.com/docs/java/new-relic-for-java

    ================================================================================
    Error executing action `run` on resource 'execute[newrelic-install]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install ----
    STDOUT: May 13, 2015 17:49:38 +0530 [4900 1] com.newrelic INFO: Agent is using Logback
    ***** ( ( o))  New Relic Java Agent Installer
    ***** Installing version 3.9.0 ...
    Could not edit start script because:
     .:. Could not locate a Tomcat, Jetty, JBoss, JBoss7 or Glassfish instance in /opt/newrelic/java
    Try re-running the install command with the -s <AppServerRootDirectory> option or from <AppServerRootDirectory>/newrelic.
    If that doesn't work, locate and edit the start script manually.
    No need to create New Relic configuration file because:
     .:. A config file already exists: /opt/newrelic/java/newrelic.yml
    ***** Install incomplete
    ***** Next steps:
    For help completing the install, see https://newrelic.com/docs/java/new-relic-for-java
    STDERR:
    ---- End output of sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install ----
    Ran sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/newrelic/recipes/java_agent.rb

     85: execute 'newrelic-install' do
     86:   command "sudo java -jar #{agent_jar} -s #{node['newrelic']['java_agent']['app_location']} #{node['newrelic']['java_agent']['agent_action']}"
     87:   only_if { node['newrelic']['java_agent']['execute_agent_action'] == true }
     88: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/newrelic/recipes/java_agent.rb:85:in `from_file'

    execute("newrelic-install") do
      action "run"
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name "newrelic"
      recipe_name "java_agent"
      only_if { #code block }
    end

[2015-05-13T17:49:38+05:30] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-05-13T17:49:38+05:30] ERROR: Running exception handlers
Running handlers complete
[2015-05-13T17:49:38+05:30] ERROR: Exception handlers complete
[2015-05-13T17:49:38+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 2 resources updated in 15.663479402 seconds
[2015-05-13T17:49:38+05:30] ERROR: execute[newrelic-install] (newrelic::java_agent line 85) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install ----
STDOUT: May 13, 2015 17:49:38 +0530 [4900 1] com.newrelic INFO: Agent is using Logback
***** ( ( o))  New Relic Java Agent Installer
***** Installing version 3.9.0 ...
Could not edit start script because:
 .:. Could not locate a Tomcat, Jetty, JBoss, JBoss7 or Glassfish instance in /opt/newrelic/java
Try re-running the install command with the -s <AppServerRootDirectory> option or from <AppServerRootDirectory>/newrelic.
If that doesn't work, locate and edit the start script manually.
No need to create New Relic configuration file because:
 .:. A config file already exists: /opt/newrelic/java/newrelic.yml
***** Install incomplete
***** Next steps:
For help completing the install, see https://newrelic.com/docs/java/new-relic-for-java
STDERR:
---- End output of sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install ----
Ran sudo java -jar /opt/newrelic/java/newrelic-agent-3.9.0.jar -s /opt/newrelic/java install returned 1
[2015-05-13T17:49:38+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Please Let me know If I need to setup anything else.

**Comment by djoos** [comment]
Hi @abhi-vaidya,

thanks for getting in touch!

Which web server are you making use of? It seems there's an issue there... (eg. ["Unable to install new relic on linux using tomcat server"](http://stackoverflow.com/questions/20852811/unable-to-install-new-relic-on-linux-using-tomcat-server))

HTH!

Kind regards,
David

**Comment by djoos** [comment]
* kick *
