### ISSUE TITLE
Manual Java agent installation is no longer possible

### ISSUE THREAD

**Issue by eric-tucker** [escapestudios-cookbooks/newrelic#198]
https://github.com/escapestudios-cookbooks/newrelic/commit/f604b4ac4bd3c8f33f9896f5b7d499adfb3ee44c

This commit took out providing the path attribute to the remote_file call that downloads the newrelic JAR.  As a result, the JAR now downloads to `/` (the root of the file system) and is not default located in `/opt/newrelic/java`.

I preferred the manual installation methods explained here:
https://docs.newrelic.com/docs/agents/java-agent/installation/java-agent-manual-installation

I download the JAR, configure the yml file, then give the -javaagent parameter when starting tomcat.  It seems that now I'm forced to enable execute_agent_action to run the JAR installer.  Is there no way to restore this behaviour?

**Comment by djoos** [comment]
Hi @eric-tucker,

we've just pushed out a few changes to the Java agent.
The JAR should download in '/opt/newrelic/java' by default. It is still possible to download the JAR-file, configure the YML-file and not make use of the execute_agent_action to run the installer...

Please give the latest version (pushing out soon) a go and we'll take it from there, thanks in advance for your feedback!

Kind regards,
David
