### ISSUE TITLE
Readme docs on newrelic_deployment still reference api_key

### ISSUE THREAD

**Issue by eric-tucker** [escapestudios-cookbooks/newrelic#201]
I recall we worked together to deprecate api_key and go with key and key_type resource input.

The example in the readme still references api_key despite key and key_type being talked about in the description for the newrelic_deployment LWRP

**Comment by djoos** [comment]
Cleaned up now, thanks @eric-tucker!

Kind regards,
David

**Comment by eric-tucker** [comment]
As always, you are fantastic at responding to issues.  Thanks David!

**Comment by djoos** [comment]
You're welcome Eric!
