### ISSUE TITLE
Opsworks Setup - could not find recipe php_agent

### ISSUE THREAD

**Issue by caffe** [escapestudios-cookbooks/newrelic#208]
Hello,

I'm following the following post in order to setup Newrelic on my Opsworks instances but am getting the error below:

https://blogs.aws.amazon.com/application-management/post/Tx1T7B0Y37JQER9/Using-New-Relic-to-monitor-applications-on-AWS-OpsWorks

============================================================================
Recipe Compile Error
============================================================================
 
 
Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe php_agent for cookbook newrelic
  
[2015-09-02T13:30:49+00:00] ERROR: Running exception handlers
[2015-09-02T13:30:49+00:00] ERROR: Exception handlers complete
[2015-09-02T13:30:49+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-09-02T13:30:49+00:00] ERROR: could not find recipe php_agent for cookbook newrelic
[2015-09-02T13:30:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
================

Any idea what could be wrong? I followed the post step by step and only corrected the recipe from newrelic::php-agent to newrelic::php_agent

Thanks,
Walter

**Comment by djoos** [comment]
Hi @caffe,

thanks for getting in touch. The article is quite out-of-date and refers to version 1.0.6 of the newrelic cookbook... In 2.0.0 we renamed a lot of recipes; in casu: php-agent.rb became php_agent.rb

Please make use of a the latest version of the cookbook and include the php_agent.rb-recipe instead...

I'll close the issue for now, but please do add a comment once you're all up and running, that would be great.

Hope this helps!

Kind regards,
David
