### ISSUE TITLE
REQUEST: Have the service_name for the php use restart instead of reload.

### ISSUE THREAD

**Issue by MiguelMoll** [escapestudios-cookbooks/newrelic#210]
Wanted to pick a few minds here before doing a (simple?) pull request. Seems on Ubuntu 12.04 and 14.04, using `service php5-fpm reload` causes php-fpm to crash. There are comments in the init script describing the issue. Since the New Relic docs explicitly say to `Restart your web server or FastCGI Process Manager (FPM).`, could we change the php_agent provider to call `restart` instead of `reload` for `service_name`? That way we can avoid other work arounds listed in the launchpad bug reports.

ref: https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1242376
ref: https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1272788

**Comment by djoos** [comment]
Hi @MiguelMoll,

thanks for reaching out!

I see your point and have to admit I'm not a big fan of having reload hard-coded either. What about this: we introduce a "service_action" attribute (default: restart as that is what the NR docs actually says to do to your web server) which then can also easily be set to reload? That way it's all a bit more flexible...

Let me know what you think!

Kind regards,
David

**Comment by MiguelMoll** [comment]
That sounds perfect! Let me know if you need help with that. I'll try to spare a few cycles.

**Comment by djoos** [comment]
Linking this issue up to #165 and #171 - code is on its way ;-)

Kind regards,
David

**Comment by djoos** [comment]
See 5c71214ac140019dfd2a13068102e44c31dbfa2b for more information! After additional testing, I'll be releasing 2.15.0 of the cookbook, including these changes.

Hope this helps!

Kind regards,
David

**Comment by MiguelMoll** [comment]
Thanks for the fast turn around! Will check this out ASAP.

**Comment by djoos** [comment]
You're welcome, let me know how it goes!

Kind regards,
David
