### ISSUE TITLE
Make `alert_policy_id` accept policy names or introduce `alert_policy_name`

### ISSUE THREAD

**Issue by rmldsky** [escapestudios-cookbooks/newrelic#214]
Hi,
Great job on the cookbook! Super useful!

One thing I'd like to ask for is a way to set alert policy (server_monitoring) by using a policy `name` instead of/in addition to `id`. Reason behind it is that policy names are easily obtainable from New Relic web interface, while policy IDs are not (one needs to query API first to get learn the ID).

I hope you at least consider adding this feature request.

Thanks!

**Comment by djoos** [comment]
Hi @rmldsky,

thanks for the feature request!

Looking up the policy to get the id (either using [policy name or policy type](https://docs.newrelic.com/docs/apis/rest-api-v2/alert-examples-v2/listing-policies-v2#single_policy)) feels to me like a feature that is out of the scope of the newrelic-cookbook... This would be needed to be able to make the API request to the ```https://api.newrelic.com/v2/alert_policies/${POLICY_ID}.json```-endpoint.

I'm closing this issue for now, but we can definitely discuss this further in this thread and I'm happy to reopen it if needed...

Thanks in advance!

Kind regards,
David

**Comment by rmldsky** [comment]
Thanks for getting back with a comment! I totally understand, just found the same cURL to query the single policy by name and though it might be somehow (easily) transformed into the method in cookbook's helpers.

Cheers!
