### ISSUE TITLE
Weird behaviour when adding server with `hostname` attribute set.

### ISSUE THREAD

**Issue by rmldsky** [escapestudios-cookbooks/newrelic#215]
I have a recipe which uses `newrelic_server_monitor` resource like this:
```
newrelic_server_monitor 'Install' do
  hostname node.name
  alert_policy_id node['my-cookbook']['server_alert_policy']
end
```
It is on AWS EC2. My instances have a default hostname in a format `ip-192-168-0-1`. When I added a cookbook and run chef-client for the first time, those nodes ended up in New Relic twice, once with `Name` as `hostname node.name` (but in default policy, not one set in the resource) and second time as the `ip-192-168-0-1` with right policy set by resource.

- Those nodes with `hostname node.name` are the one where data from machine goes (per *.cfg file?)
- Those nodes with `ip-192-168-0-1` get "greyed out" after some time due to lack of data, but each next chef-client run refreshes this in New Relic.
- Those nodes with `hostname node.name` do not get the `alert_policy_id node['my-cookbook']['server_alert_policy']` set, but gets the default policy from New Relic.

Not sure why the system hostname takes precedence over what I put in the resource file.

I do have other EC2 nodes where `node.name` from Chef server matches `$ hostname` on the Linux system and those end up in New Relic correctly (as expected), only once.

Phew. Hope I am clear of what the problem is. If I can help with debugging further let me know. Also not sure if this is `newrelic` cookbook, or NewRelic's `nrsysmond` or API.

EDIT: When  I run `service newrelic-sysmond restart` on one of the machines with Name as `ip-192-168-0-1` manually it does not get "refreshed" in New Relic. But when I re-run chef-client - it does.

EDIT 2: I think this is the reason:

```
    * template[/etc/newrelic/nrsysmond.cfg] action create
      - update content in file /etc/newrelic/nrsysmond.cfg from 707f3b to 0706ef
      --- /etc/newrelic/nrsysmond.cfg	2015-09-18 13:35:39.331646620 +0000
      +++ /tmp/chef-rendered-template20150918-1154-1162g37	2015-09-18 13:58:25.887646620 +0000
      @@ -100,7 +100,7 @@
       # Default: Whatever the system calls the host.
       # Note   : Can also be set with the -n command line option.
       #
      -hostname=<MY NODE HOSTNEM GOES HERE FROM RESOURCE>
>>>     +#hostname= 

       #
       # Option : labels
    * service[newrelic-sysmond] action enable (up to date)
    * service[newrelic-sysmond] action start (up to date)
    * service[newrelic-sysmond] action restart
>>>      - restart service service[newrelic-sysmond]

Recipe: my-cookbook::_newrelic
  * newrelic_server_monitor[Install] action install
    * apt_repository[newrelic] action add
      * remote_file[/var/chef/cache/548C16BF.gpg] action create (up to date)
      * execute[install-key 548C16BF.gpg] action run (skipped due to not_if)
      * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
      * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
      * execute[apt-get update] action nothing (skipped due to action :nothing)
      * file[/etc/apt/sources.list.d/newrelic.list] action create (up to date)
       (up to date)
    * package[newrelic-sysmond] action install (up to date)
    * template[/etc/newrelic/nrsysmond.cfg] action create
      - update content in file /etc/newrelic/nrsysmond.cfg from 0706ef to 707f3b
      --- /etc/newrelic/nrsysmond.cfg	2015-09-18 13:58:25.887646620 +0000
      +++ /tmp/chef-rendered-template20150918-1154-90g9x8	2015-09-18 13:58:28.263646620 +0000
      @@ -100,7 +100,7 @@
       # Default: Whatever the system calls the host.
       # Note   : Can also be set with the -n command line option.
       #
      -#hostname=
      +hostname=<MY NODE HOSTNEM GOES HERE FROM RESOURCE>

       #
       # Option : labels
    * service[newrelic-sysmond] action enable (up to date)
    * service[newrelic-sysmond] action start (up to date)
    * ruby_block[Move server to newrelic decommissioned policy] action run
      - execute the ruby block Move server to newrelic decommissioned policy
    * service[newrelic-sysmond] action restart
      - restart service service[newrelic-sysmond]
    * service[newrelic-sysmond] action restart
      - restart service service[newrelic-sysmond]
``` 
It seems that with each chef-client run ` template[/etc/newrelic/nrsysmond.cfg] action create` is being trigger. First it overwrites exiting `nrsysmond.cfg`, and cleans the `hostname=`, restart `nrsysmond` service (hence New Relic gets the  `ip-192-168-0-1` node), then again the template is regenerated this time from within `newrelic_server_monitor` resource in my-cookbook, `hostname=` gets added, service is restarted and New Relic gets a node second time with desired hostname.

**Q:** Why is it happening that the template is being recreated every chef-client run?

**Comment by rmldsky** [comment]
OK, it seems a wrapper cookbook pattern does not work with newrelic-cookbook, or I am using it wrong. Might be that the desired way to use is by setting attributes and not using resource with attributes. I have changed this:
```
include_recipe 'newrelic'

newrelic_server_monitor 'Install' do
  hostname node.name
  alert_policy_id node['my-cookbook']['server_alert_policy']
end
```
to this:
```
node.default['newrelic']['server_monitoring']['hostname'] = node.name
node.default['newrelic']['server_monitoring']['alert_policy_id'] = node['my-cookbook']['newrelic']['server_alert_policy']

include_recipe 'newrelic'
```
And it works as desired now.

Any way would like to know your thoughts about this one, I mean the attributes vs. wrapper cookbook.

Thanks!

**Comment by djoos** [comment]
Hi @rmldsky,

thanks for getting in touch! A quick reply from my mobile :-)

Either pattern should be possible, however: in the first example you include the 'newrelic' default recipe before making use of the resource directly, and the default recipe you included will install the server monitor. It seems that afterwards you use the LWRP then to, in effect, run it again with different attributes set on the LWRP.

To fix your first example, just include newrelic in your wrapper cookbook's metadata and use the resource:
newrelic_server_monitor 'Install' do
  hostname node.name
  alert_policy_id node['my-cookbook']['server_alert_policy']
end

Hope this helps!

Kind regards,
David

**Comment by rmldsky** [comment]
Thanks for taking your time to answer this one. Yup, it seems I have been mixing those two approaches.
From a quick test it works OK with LWRP only (without `include_recipe`), thou it needed also `license` parameter set as it was not picking up one being set via `node.default`.

Cheers!
Dawid

**Comment by djoos** [comment]
Hi Dawid,

no worries!

Re: not picking up license set via ```node.default```
```node.default``` is not going to work as the license is initialized to nil (```default['newrelic']['license'] = nil```). node.set should do the trick, or alternatively using the ```license``` attribute on the LWRP...

Hope this helps!

Kind regards,
David
