### ISSUE TITLE
Chef 13 Compatibility

### ISSUE THREAD

**Issue by Rockstar04** [escapestudios-cookbooks/newrelic#217]
Looks like there may be some problems when chef 13 comes out (whenever that may be)

Here is the output from one of my chef runs

```
  Cannot specify both default and name_property together on property app_path of resource newrelic_agent_nodejs. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
    - /var/chef/cache/cookbooks/newrelic/resources/agent_nodejs.rb:15:in `class_from_file'
  Cannot specify both default and name_property together on property key of resource newrelic_deployment. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
    - /var/chef/cache/cookbooks/newrelic/resources/deployment.rb:13:in `class_from_file'
  Cannot specify both default and name_property together on property app_name of resource newrelic_deployment. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
    - /var/chef/cache/cookbooks/newrelic/resources/deployment.rb:18:in `class_from_file'
```

Currently I dont know enough about creating, or maintaining LWRPs and Resources to submit a PR.

**Comment by sahilsk** [comment]
Indeed. These warning messages are very verbose too. Any quick fix here would be great.

**Comment by sahilsk** [comment]
I have tried to fixed them here: https://github.com/escapestudios-cookbooks/newrelic/pull/226

**Comment by eric-tucker** [comment]
Throwing in my +1 for this fix.  I don't want Newrelic breaking when we move to Chef 13.

**Comment by djoos** [comment]
@sahilsk's PR (226) got merged.

I'll close this issue for now, but happy to hear if there are any other fixes required...

Kind regards,
David

**Comment by crokobit** [comment]
+1 :dancer: 
thx ~
