### ISSUE TITLE
OpsWorks - newrelic::php-agent exception

### ISSUE THREAD

**Issue by onema** [escapestudios-cookbooks/newrelic#56]
I'm testing this  cookbook on AWS OpsWorks. The recipe `newrelic::default` works perfect, but the recipe `newrelic::php-agent` throws the following error:

```
FATAL: Chef::Exceptions::RecipeNotFound: ruby_block[Compile Custom OpsWorks Run List] 
(opsworks_custom_cookbooks::execute line 3) had an error: 
Chef::Exceptions::RecipeNotFound: could not find recipe default for cookbook php
```

Using Chef 11.4
I'm setting both `node[newrelic][server_monitoring][license]` and `node[newrelic][application_monitoring][license]` with the proper license keys. 

Any idea what is going on?

**Comment by gentitope** [comment]
Hello David,

I have issue installing python agent.

Find the error below:
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/recipes/python_agent.rb
================================================================================
 
 
NoMethodError
-------------
No resource or method named `python_pip' for `Chef::Recipe "python_agent"'
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/recipes/python_agent.rb:12:in `from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/recipes/python_agent.rb:
 
5:  # Copyright 2012-2014, Escape Studios
6:  #
7: 
8:  include_recipe 'newrelic::repository'
9: 
10:  license = node['newrelic']['application_monitoring']['license']
11: 
12>> python_pip 'newrelic' do
13:    if node['newrelic']['python_agent']['python_venv']
14:      virtualenv node['newrelic']['python_agent']['python_venv']
15:    end
16:    action node['newrelic']['python_agent']['agent_action']
17:    if node['newrelic']['python_agent']['python_version'] != 'latest'
18:      version node['newrelic']['python_agent']['python_version']
19:    end
20:  end
21:

**Comment by djoos** [comment]
Hi @gentitope,

could you make sure to include the python (default) recipe in your run list?
I'll try to have a look at some better error checking though...

Hope this helps!

Kind regards,
David

**Comment by kepps2113** [comment]
If anyone else finds this thread, note there's a similar issue regarding php-agent here: https://github.com/escapestudios-cookbooks/newrelic/issues/208

It appears it's been renamed to php_agent, and updating your recipe name should solve a lot of problems.
