### ISSUE TITLE
Not upgrading package on Ubuntu through APT

### ISSUE THREAD

**Issue by GuyPaddock** [escapestudios-cookbooks/newrelic#93]
We're running the latest New Relic Chef cookbook (1.0.5) but it does not look like it's upgrading the existing New Relic packages on the affected nodes.

We get the warning "The following apps' agents require a security update for their Postgres explain plan support:..." when logging-in to NR, and the nodes listed are those that received New Relic through Chef the longest time ago.

If I run "apt-get install newrelic-sysmond" directly, APT offers to upgrade the NR package.

We are running Ubuntu 12.04.2 LTS.

We are invoking the NR chef cookbook from our own cookbook. Here's the snippet from our `default.rb` file:

``` ruby
include_recipe 'newrelic::repository'
include_recipe 'newrelic::server-monitor-agent'
include_recipe 'newrelic::python-agent'
```

**Comment by welearnednothing** [comment]
Just a head's up: upgrading the server monitor agent is failing with the following error:

```
Setting up newrelic-sysmond (2.0.2.111) ...
STDERR: Configuration file `/etc/newrelic/nrsysmond.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nrsysmond.cfg (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing newrelic-sysmond (--configure):
 EOF on stdin at conffile prompt
Errors were encountered while processing:
 newrelic-sysmond
E: Sub-process /usr/bin/dpkg returned an error code (1)
---- End output of apt-get -q -y install newrelic-sysmond=2.0.2.111 ----
Ran apt-get -q -y install newrelic-sysmond=2.0.2.111 returned 100
[2015-02-25T16:27:49-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
I'll file a ticket, but I figured it was relevant to the folks on this thread. Also it would be nice to have the new properties for this listed in the docs :)

I'll try to find time to put together a PR, but if anyone wants to beat me to it, feel free!

**Comment by djoos** [comment]
see #157 (@welearnednothing)
